"""Query object"""
type Query {
  sharedInfo(virtualPath: String): SharedInfo!
}

"""The Long scalar type represents a signed 64-bit numeric non-fractional value"""
scalar Long

type SharedFile {
  name: String!
  virtualPath: String!
  isDir: Boolean!
  size: Long!
  mimeType: String!
  hasThumb: Boolean!
}

type SharedInfo {
  name: String!
  readOnly: Boolean!
  requiresPassword: Boolean!
  expiresAt: Long
  urlToken: String!
  entries: [SharedFile!]!
}

"""The Short scalar type represents a signed 16-bit numeric non-fractional value"""
scalar Short

type __Directive {
  name: String!
  description: String
  locations: [__DirectiveLocation!]!
  args: [__InputValue!]!
}

enum __DirectiveLocation {
  QUERY
  MUTATION
  SUBSCRIPTION
  FIELD
  FRAGMENT_DEFINITION
  FRAGMENT_SPREAD
  INLINE_FRAGMENT
}

type __EnumValue {
  name: String!
  description: String
  isDeprecated: Boolean!
  deprecationReason: String
}

type __Field {
  name: String!
  description: String
  type: __Type!
  args: [__InputValue!]!
  isDeprecated: Boolean!
  deprecationReason: String
}

type __InputValue {
  name: String!
  description: String
  type: __Type!
  defaultValue: String
}

type __Schema {
  types: [__Type!]!
  queryType: __Type!
  mutationType: __Type
  subscriptionType: __Type
  directives: [__Directive!]!
}

type __Type {
  kind: __TypeKind!
  name: String
  description: String!
  fields(includeDeprecated: Boolean): [__Field!]
  interfaces: [__Type!]
  possibleTypes: [__Type!]
  enumValues(includeDeprecated: Boolean): [__EnumValue!]
  inputFields: [__InputValue!]
  ofType: __Type
}

enum __TypeKind {
  SCALAR
  OBJECT
  INTERFACE
  UNION
  ENUM
  INPUT_OBJECT
  LIST
  NON_NULL
}
