package com.ismartcoding.plain.platform

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

/**
 * Unit tests for [generateEd25519KeyPair].
 *
 * Regression coverage for the crash where the previous brittle byte-pattern
 * parsing (`0x1a 0x20`) of Tink's serialized keyset JSON failed on fresh
 * installs, throwing "Failed to extract raw Ed25519 private key from keyset".
 * The fix uses Tink's public [Ed25519Sign.KeyPair.newKeyPair] API which
 * returns raw 32-byte keys directly.
 */
class PairingCryptoEd25519Test {

    @Test
    fun generatedPrivateKeyIs32Bytes() {
        val (privateKey, _) = generateEd25519KeyPair()
        assertEquals(32, privateKey.size, "Ed25519 private key must be 32 bytes")
    }

    @Test
    fun generatedPublicKeyIs32Bytes() {
        val (_, publicKey) = generateEd25519KeyPair()
        assertEquals(32, publicKey.size, "Ed25519 public key must be 32 bytes")
    }

    @Test
    fun differentCallsProduceDifferentKeys() {
        val (privA, pubA) = generateEd25519KeyPair()
        val (privB, pubB) = generateEd25519KeyPair()
        assertNotEquals(privA.toList(), privB.toList(), "private keys must differ")
        assertNotEquals(pubA.toList(), pubB.toList(), "public keys must differ")
    }

    @Test
    fun generatedKeyPairCanSignAndVerify() {
        val (privateKey, publicKey) = generateEd25519KeyPair()
        val data = "hello world".encodeToByteArray()
        val signature = signEd25519(privateKey, data)
        assertTrue(
            verifyEd25519(publicKey, data, signature),
            "signature generated by the new key pair must verify",
        )
    }

    @Test
    fun signatureFailsWithWrongPublicKey() {
        val (privateKey, _) = generateEd25519KeyPair()
        val (_, wrongPublicKey) = generateEd25519KeyPair()
        val data = "hello world".encodeToByteArray()
        val signature = signEd25519(privateKey, data)
        assertTrue(
            !verifyEd25519(wrongPublicKey, data, signature),
            "verification with a wrong public key must fail",
        )
    }

    @Test
    fun signatureFailsWithTamperedData() {
        val (privateKey, publicKey) = generateEd25519KeyPair()
        val data = "hello world".encodeToByteArray()
        val signature = signEd25519(privateKey, data)
        val tampered = "hello WORLD".encodeToByteArray()
        assertTrue(
            !verifyEd25519(publicKey, tampered, signature),
            "verification of tampered data must fail",
        )
    }
}
