package com.ismartcoding.plain.platform

import com.ismartcoding.plain.TempData
import com.ismartcoding.plain.enums.HttpServerState
import com.ismartcoding.plain.events.HttpServerStateChangedEvent
import com.ismartcoding.plain.helpers.TimeHelper
import com.ismartcoding.plain.helpers.coIO
import com.ismartcoding.plain.helpers.withIO
import com.ismartcoding.plain.lib.channel.sendEvent
import com.ismartcoding.plain.lib.logcat.LogCat
import com.ismartcoding.plain.web.HttpServerManager
import io.ktor.client.request.get
import io.ktor.http.HttpStatusCode
import kotlinx.coroutines.delay
import kotlinx.coroutines.withTimeoutOrNull

/**
 * iOS implementation of the HTTP server platform contract, backed by the
 * SwiftNIO server living in the iosApp Swift target.
 *
 * The Swift `PlainHttpServer` class implements [IosHttpServerBridge] and
 * registers itself with [IosPlatformRegistry] at app startup
 * (see `iosApp.swift`). Kotlin drives the lifecycle through that bridge; per
 * request dispatch is handled by [IosRequestProcessor].
 */

actual fun httpServerPortsInUse(): Set<Int> = HttpServerManager.portsInUse.toSet()

actual fun getSSLSignature(password: String): ByteArray = ByteArray(0)

actual fun generateSSLKeyStore(password: String) {
    // iOS uses NIOSSL with an in-memory self-signed certificate generated by
    // Swift; no keystore file is needed. Kept as a no-op for contract parity.
}

actual suspend fun resetPasswordAsync(): String = HttpServerManager.resetPasswordAsync()

actual suspend fun checkHttpServerAsync(): Boolean = withIO {
    val port = TempData.httpPort.value
    val url = "http://127.0.0.1:$port/health"
    withTimeoutOrNull(9_000) {
        val client = createHttpClient()
        val deadline = TimeHelper.nowMillis() + 8_500L
        var healthy = false
        while (!healthy && TimeHelper.nowMillis() < deadline) {
            try {
                val response = client.get(url)
                if (response.status == HttpStatusCode.OK) {
                    healthy = true
                }
            } catch (ex: Exception) {
                delay(300)
                LogCat.e("iOS HTTP server check failed: ${ex.message}")
            }
        }
        LogCat.d("iOS HTTP server check healthy: $healthy")
        healthy
    } ?: false
}

actual suspend fun disposeHttpServer() {
    kotlinx.coroutines.delay(100)
    IosPlatformRegistry.httpServerBridge()?.stop()
}

actual suspend fun stopHttpServiceAsync(): Unit = withIO {
    sendEvent(HttpServerStateChangedEvent(HttpServerState.STOPPING))
    try {
        // Best-effort graceful shutdown via /shutdown endpoint.
        val port = TempData.httpPort.value
        val client = createHttpClient()
        client.get("http://127.0.0.1:$port/shutdown")
    } catch (_: Exception) {}
    IosPlatformRegistry.httpServerBridge()?.stop()
    HttpServerManager.httpServerError = ""
    HttpServerManager.portsInUse.clear()
    sendEvent(HttpServerStateChangedEvent(HttpServerState.OFF))
}

actual fun startHttpServerService() {
    val bridge = IosPlatformRegistry.httpServerBridge()
    if (bridge == null) {
        LogCat.e("iOS HTTP server bridge not registered — Swift PlainHttpServer missing")
        sendEvent(HttpServerStateChangedEvent(HttpServerState.ERROR))
        return
    }
    coIO {
        LogCat.d("startHttpServer (iOS/SwiftNIO)")
        sendEvent(HttpServerStateChangedEvent(HttpServerState.STARTING))
        HttpServerManager.portsInUse.clear()
        HttpServerManager.httpServerError = ""

        val httpPort = TempData.httpPort.value
        val httpsPort = TempData.httpsPort.value

        var started = false
        var lastError: String? = null
        for (attempt in 1..3) {
            // Stop any previous instance so the ports are free.
            bridge.stop()
            delay(500)
            try {
                started = bridge.start(httpPort, httpsPort)
                if (started) break
            } catch (ex: Exception) {
                lastError = ex.message
                LogCat.e("Server start attempt $attempt/3 failed: ${ex.message}")
            }
        }

        if (!started) {
            HttpServerManager.portsInUse.add(httpPort)
            HttpServerManager.portsInUse.add(httpsPort)
            HttpServerManager.httpServerError = lastError ?: "Failed to start HTTP server"
            sendEvent(HttpServerStateChangedEvent(HttpServerState.ERROR))
            return@coIO
        }

        // Wait for the server to become healthy.
        val healthy = checkHttpServerAsync()
        if (healthy) {
            HttpServerManager.httpServerError = ""
            HttpServerManager.portsInUse.clear()
            sendEvent(HttpServerStateChangedEvent(HttpServerState.ON))
            LogCat.d("iOS HTTP server started on port $httpPort")
        } else {
            bridge.stop()
            HttpServerManager.httpServerError = "Health check failed"
            sendEvent(HttpServerStateChangedEvent(HttpServerState.ERROR))
        }
    }
}
