package com.ismartcoding.plain.crypto

import com.ismartcoding.plain.platform.PairingCrypto
import com.ismartcoding.plain.platform.chaCha20Decrypt
import com.ismartcoding.plain.platform.verifyEd25519Signature
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Verifies that plain-app (Kotlin / Google Tink / BouncyCastle) can decrypt
 * and verify crypto material generated by plain-web's JavaScript stack
 * (@noble/curves, @noble/ciphers, @noble/hashes).
 *
 * Vectors are generated by `scripts/generate-web-crypto-vectors.mjs` in
 * plain-web and stored in `commonTest/resources/web-crypto-vectors.json`.
 */
class WebCryptoVectorTest {

    @Test
    fun ecdh_computes_same_shared_key_as_web() {
        val v = loadVectors().ecdh
        val privA = b64Decode(v.privateKeyA)
        val pubB = b64Decode(v.publicKeyB)

        assertEquals(32, privA.size, "private key A must be 32 bytes")
        assertEquals(65, pubB.size, "public key B must be 65 bytes (X9.63)")
        assertEquals(0x04, pubB[0], "public key B must start with 0x04")

        val shared = PairingCrypto.computeECDHSharedKey(privA, pubB)
        assertNotNull(shared, "ECDH shared key computation must not return null")
        assertEquals(v.sharedKey, shared, "plain-app ECDH shared key must match web's")
    }

    @Test
    fun ecdh_symmetry_b_to_a() {
        val v = loadVectors().ecdh
        val privB = b64Decode(v.privateKeyB)
        val pubA = b64Decode(v.publicKeyA)

        val shared = PairingCrypto.computeECDHSharedKey(privB, pubA)
        assertNotNull(shared, "ECDH shared key computation must not return null")
        assertEquals(v.sharedKey, shared, "ECDH(B_priv, A_pub) must equal ECDH(A_priv, B_pub)")
    }

    @Test
    fun ed25519_verifies_web_signature() {
        val v = loadVectors().ed25519
        val pub = b64Decode(v.publicKey)
        val sig = b64Decode(v.signature)

        assertEquals(32, pub.size, "public key must be 32 bytes")
        assertEquals(64, sig.size, "signature must be 64 bytes")

        val ok = PairingCrypto.verifyEd25519(pub, v.message.toByteArray(), sig)
        assertTrue(ok, "plain-app must verify web's Ed25519 signature")
    }

    @Test
    fun ed25519_verify_via_platform_function() {
        val v = loadVectors().ed25519
        val ok = verifyEd25519Signature(
            b64Decode(v.publicKey),
            v.message.toByteArray(),
            b64Decode(v.signature),
        )
        assertTrue(ok, "verifyEd25519Signature must accept web's signature")
    }

    @Test
    fun ed25519_rejects_tampered_signature() {
        val v = loadVectors().ed25519
        val tampered = b64Decode(v.signature).copyOf()
        tampered[0] = (tampered[0].toInt() xor 0x01).toByte()

        val ok = PairingCrypto.verifyEd25519(b64Decode(v.publicKey), v.message.toByteArray(), tampered)
        assertTrue(!ok, "tampered signature must fail verification")
    }

    @Test
    fun xchacha20_decrypts_web_ciphertext() {
        val v = loadVectors().xchacha20
        val key = b64Decode(v.key)
        val nonce = b64Decode(v.nonce)
        val ciphertext = b64Decode(v.ciphertext)

        assertEquals(32, key.size, "key must be 32 bytes")
        assertEquals(24, nonce.size, "nonce must be 24 bytes")
        assertEquals(
            v.plaintext.toByteArray().size + 16,
            ciphertext.size,
            "ciphertext length must be plaintext + 16-byte tag",
        )

        val blob = ByteArray(nonce.size + ciphertext.size)
        System.arraycopy(nonce, 0, blob, 0, nonce.size)
        System.arraycopy(ciphertext, 0, blob, nonce.size, ciphertext.size)

        val decrypted = chaCha20Decrypt(key, blob)
        assertNotNull(decrypted, "decryption must succeed")
        assertEquals(v.plaintext, decrypted.decodeToString(), "decrypted plaintext must match web's")
    }

    @Test
    fun xchacha20_decrypt_rejects_wrong_key() {
        val v = loadVectors().xchacha20
        val nonce = b64Decode(v.nonce)
        val ciphertext = b64Decode(v.ciphertext)
        val wrongKey = ByteArray(32)

        val blob = ByteArray(nonce.size + ciphertext.size)
        System.arraycopy(nonce, 0, blob, 0, nonce.size)
        System.arraycopy(ciphertext, 0, blob, nonce.size, ciphertext.size)

        val result = chaCha20Decrypt(wrongKey, blob)
        assertTrue(result == null, "decryption with wrong key must fail")
    }

    @Test
    fun base64_known_value_matches() {
        val v = loadVectors().base64
        val input = v.input.map { it.toByte() }.toByteArray()
        assertEquals(v.output, b64Encode(input), "base64 encoding must match web's")
    }

    @Test
    fun hex_known_value_matches() {
        val v = loadVectors().hex
        val input = v.input.map { it.toByte() }.toByteArray()
        val hex = input.joinToString("") { (it.toInt() and 0xFF).toString(16).padStart(2, '0') }
        assertEquals(v.output, hex, "hex encoding must match web's")
    }

    // ── Vector loading ─────────────────────────────────────────────────────────

    private data class WebVectors(
        val ecdh: EcdhV,
        val ed25519: Ed25519V,
        val xchacha20: XChaChaV,
        val base64: Base64V,
        val hex: HexV,
    )

    private data class EcdhV(
        val privateKeyA: String,
        val publicKeyA: String,
        val privateKeyB: String,
        val publicKeyB: String,
        val sharedKey: String,
    )

    private data class Ed25519V(
        val privateKey: String,
        val publicKey: String,
        val message: String,
        val signature: String,
    )

    private data class XChaChaV(
        val key: String,
        val nonce: String,
        val plaintext: String,
        val ciphertext: String,
    )

    private data class Base64V(val input: List<Int>, val output: String)
    private data class HexV(val input: List<Int>, val output: String)

    private fun loadVectors(): WebVectors {
        val cl = Thread.currentThread().contextClassLoader
        val json = cl?.getResourceAsStream("web-crypto-vectors.json")
            ?: WebCryptoVectorTest::class.java.getResourceAsStream("/web-crypto-vectors.json")
            ?: error("web-crypto-vectors.json not found on test classpath")
        return json.bufferedReader().use { it.readText() }.let(::parseVectors)
    }

    private fun parseVectors(json: String): WebVectors {
        val ecdh = parseObject(json, "ecdh")
        val ed25519 = parseObject(json, "ed25519")
        val xchacha20 = parseObject(json, "xchacha20")
        val base64 = parseObject(json, "base64")
        val hex = parseObject(json, "hex")

        return WebVectors(
            ecdh = EcdhV(
                privateKeyA = parseString(ecdh, "privateKeyA"),
                publicKeyA = parseString(ecdh, "publicKeyA"),
                privateKeyB = parseString(ecdh, "privateKeyB"),
                publicKeyB = parseString(ecdh, "publicKeyB"),
                sharedKey = parseString(ecdh, "sharedKey"),
            ),
            ed25519 = Ed25519V(
                privateKey = parseString(ed25519, "privateKey"),
                publicKey = parseString(ed25519, "publicKey"),
                message = parseString(ed25519, "message"),
                signature = parseString(ed25519, "signature"),
            ),
            xchacha20 = XChaChaV(
                key = parseString(xchacha20, "key"),
                nonce = parseString(xchacha20, "nonce"),
                plaintext = parseString(xchacha20, "plaintext"),
                ciphertext = parseString(xchacha20, "ciphertext"),
            ),
            base64 = Base64V(
                input = parseIntArray(base64, "input"),
                output = parseString(base64, "output"),
            ),
            hex = HexV(
                input = parseIntArray(hex, "input"),
                output = parseString(hex, "output"),
            ),
        )
    }

    private fun parseObject(json: String, key: String): String {
        val pattern = "\"$key\"\\s*:\\s*\\{"
        val startMatch = Regex(pattern).find(json)
            ?: error("key '$key' not found in JSON")
        val start = startMatch.range.last + 1
        var depth = 1
        var i = start
        while (i < json.length && depth > 0) {
            when (json[i]) {
                '{' -> depth++
                '}' -> depth--
            }
            i++
        }
        return json.substring(start, i - 1)
    }

    private fun parseString(obj: String, key: String): String {
        val pattern = "\"$key\"\\s*:\\s*\"((?:[^\"\\\\]|\\\\.)*)\""
        val match = Regex(pattern).find(obj)
            ?: error("string key '$key' not found in object")
        return match.groupValues[1]
            .replace("\\\"", "\"")
            .replace("\\\\", "\\")
    }

    private fun parseIntArray(obj: String, key: String): List<Int> {
        val pattern = "\"$key\"\\s*:\\s*\\[([^\\]]*)\\]"
        val match = Regex(pattern).find(obj)
            ?: error("array key '$key' not found in object")
        return match.groupValues[1]
            .split(",")
            .mapNotNull { it.trim().toIntOrNull() }
    }

    private fun b64Decode(s: String): ByteArray = java.util.Base64.getDecoder().decode(s)
    private fun b64Encode(b: ByteArray): String = java.util.Base64.getEncoder().encodeToString(b)
}
