package com.ismartcoding.plain.ui.page

enum class RouteName {
    HOME,
    SETTINGS,
    LANGUAGE,
    COLOR_AND_STYLE,
    DARK_THEME,
    BACKUP_RESTORE,
    ABOUT,
    WEB_SETTINGS,
    WEB_SECURITY,
    WEB_LEARN_MORE,
    TEXT,
    SESSIONS,
    WEB_DEV,
    EXCHANGE_RATE,
    SOUND_METER,
    CHAT,
    CHAT_TEXT,
    CHAT_EDIT_TEXT,
    SCAN,
    SCAN_HISTORY,
    MEDIA_PREVIEW,
    APPS,
    OTHER_FILE,
    DOCS,
    NOTES,
    TAGS,
    PDF_VIEWER,
    FEEDS,
    FEED_ENTRIES,
    FEED_SETTINGS,
    AUDIO,
    AUDIO_PLAYER,
    TEXT_FILE,
}
