package com.ismartcoding.plain.ui.page

enum class RouteName {
    HOME,
    SETTINGS,
    LANGUAGE,
    COLOR_AND_STYLE,
    DARK_THEME,
    BACKUP_RESTORE,
    ABOUT,
    LOGS,
    WEB_CONSOLE,
    WEB_SECURITY,
    PASSWORD,
    TEXT,
    SESSIONS,
    WEB_DEV,
    EXCHANGE_RATE,
    SOUND_METER,
    CHAT,
    CHAT_TEXT,
    CHAT_EDIT_TEXT,
    SCAN,
    SCAN_HISTORY,
    MEDIA_PREVIEW,
    APPS,
}
